---
# tasks file for nginx_vagrant_vm

- name: Copy the user public key into the Vagrant VM for the Vagrant user
  ansible.posix.authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"

- name: Install epel-release
  yum:
    name: 'epel-release'
    state: latest
  become: yes

- name: Install tracer
  yum:
    name: 'tracer'
    state: latest
  become: yes 

- name: Update the OS
  yum:
    name: '*'
    state: latest
  become: yes

- name: permit traffic in default zone for http service
  ansible.posix.firewalld:
    service: http
    permanent: yes
    state: enabled

- name: permit traffic in default zone for https service
  ansible.posix.firewalld:
    service: https
    permanent: yes
    state: enabled

- name: Install ca-certificates
  yum:
    name: 'ca-certificates'
    state: latest
  become: yes

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /etc/ssl/nginx
    state: directory
    mode: '0755'

- name: Copy the NGINX key
  copy:
    src: ~/secrets/nginx-repo.key
    dest: /etc/ssl/nginx/nginx-repo.key
    owner: root
    group: root
    mode: 0644
  become: true


- name: Copy the NGINX certificate
  copy:
    src: ~/secrets/nginx-repo.crt
    dest: /etc/ssl/nginx/nginx-repo.crt
    owner: root
    group: root
    mode: 0644
  become: true

- name: Add the nginx repo
  template:
    src: etc/yum.repos.d/nginx-plus.repo
    dest: /etc/yum.repos.d/nginx-plus.repo
    owner: root
    group: root
    mode: '0644'
    backup: no
  become: true


- name: Install nginx-plus
  yum:
    name: 'nginx-plus'
    state: latest
  notify: nginx_service
  become: yes


- name: Install App Protect
  yum:
    name: 'app-protect'
    state: latest
  notify: nginx_service
  become: yes

#- name: Install App Protect Signatures
#  yum:
#    name: 'app-protect-attack-signatures'
#    state: latest
#  become: yes

- name: Update the NGINX config
  template:
    src: etc/nginx/nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: '0644'
    backup: no
  notify: nginx_service
  become: true

- name: Update the NGINX default site config
  template:
    src: etc/nginx/conf.d/default.conf
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: '0644'
    backup: no
  notify: nginx_service
  become: true

- name: Install vim
  yum:
    name: 'vim'
    state: latest
  become: yes



- debug: var=ansible_all_ipv4_addresses
